name: Swift CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'  # Especifica la versión de Xcode que deseas usar

      - name: Build app
        run: xcodebuild -scheme ControlaTuLana -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' build

      - name: Run tests
        run: xcodebuild -scheme ControlaTuLana -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' test
